### ISSUE TITLE
Unsupported long argument

### ISSUE THREAD

**Issue by lodener** [frodenas/alertmanager-resource#1]
After the update of alertmanager to v0.13.0, the amtool seems to be no longer accepting the '--author' flag as it is. Whenever we call the resource, it returns the following error:

`amtool: error: unknown long flag '--author'`

It might be that the command (`silence add`) has to precede the flags?

**Comment by frodenas** [comment]
Thanks @lodener for reporting this, and apologies for the bug :( I've fixed it at https://github.com/frodenas/alertmanager-resource/commit/333f64bace997bd9ae0c6f1409a75bc7c1d8fa9b, and a new docker image with the fix has been pushed to docker hub.

I'll keep this issue open until you have a chance to test it. Thanks!

**Comment by metskem** [comment]
I just tested it (@lodener is my colleague, and he is off today), but it shows some weirdness.
I do get the output, but the resource fails (small red cross on the right side of the screen), see attached screen print.

Cheers,
Harry
<img width="1296" alt="screen shot 2018-02-07 at 14 55 14" src="https://user-images.githubusercontent.com/555693/35920561-7ad55038-0c18-11e8-928d-1cf6e3c7d016.png">

**Comment by metskem** [comment]
Happens both on concourse 3.3.3 and 3.8.0 BTW.

regards,
Harry

**Comment by frodenas** [comment]
is this something that was already happening? or only after the upgrade of the `amtool`?

**Comment by lodener** [comment]
It did not happen before.

Using the new resource, the silence is however succesfully added to the alertmanager. When manually running the amtool using the same payload there are no errors or non-zero exitcodes returned. Not sure what's happening/causing the failure...

**Comment by lodener** [comment]
When manually running the in script from a hijacked container that's part of the failed pipeline, it all seems to be working: valid output and an exit code of 0. However when run from the actual pipeline, the task fails.

@frodenas any pointers on where to look for the cause?

**Comment by lodener** [comment]
@frodenas we've done some more troubleshooting, and it seems that the '--expired' options being used in the 'in' call to amtool **only** displays the silences that have already expired, excluding the active silences resulting in an exit code 4.

The updated amtool doesn't seem to provide an option to display both in one call. Would it be possible to build an array containing both the active and expired silences, so that both the add and expire can successfully make use of it?

**Comment by frodenas** [comment]
This should have been fixed in the latest release.

To avoid problems in the future I've started using versioning for the [frodenas/alertmanager-resource](https://hub.docker.com/r/frodenas/alertmanager-resource/tags/) docker image:

* `master` will contain the latest changes to the `master` branch
* `latest` will contain the latest [release](https://github.com/frodenas/alertmanager-resource/releases)
* `v*.*.*` will contains specific release/tag versions

So in case there's a problem when using `latest`, the fallback mechanism will be to use a version tagged image.
